### ISSUE TITLE
抓寵後是不是就不能同步走路了？

### ISSUE THREAD

**Issue by chuhw** [wangpy/PokemonMapWalker#5]
目前測試走路一切正常，但抓寵結束後，發現 xcode app 和手機就失去同步了
請問是只有我遇到這個問題嗎 XD

**Comment by j796160836** [comment]
偶爾不時的斷線是正常的，因為 iOS 本身記憶體調配的關係，當記憶體快不足時，會優先砍在背景app

**Comment by wangpy** [comment]
請問Johnny的建議有解決您的問題嗎? 或許之後可以改進一下AppleScript可以偵測iOS app是否有在執行並且重跑...

**Comment by chuhw** [comment]
再請問一下，如果是 "當記憶體快不足時，會優先砍在背景app" 就是在重跑一次程式嗎？

**Comment by wangpy** [comment]
1. 看XCode的 LocationSimulation app 的 Debug session 是否還在執行
2. 如果沒有執行了代表他應該是被砍了, 直接從XCode 重跑debug session, (這邊建議手動點一下Simulate location -> MapWalker) 然後再切到遊戲, 應該會立刻移動到MapWalker最後的位置
3. 再使用MapWalker app做移動應該就會恢復正常了.
4. 如果Debug session還在執行中, 可能要確認一下XCode畫面是否確實是如下圖所示的狀態.
   ![13908944_10154023348514055_2330401733147307657_o](https://cloud.githubusercontent.com/assets/97795/17656152/df5dd60e-62e8-11e6-9538-a3407e9c16a4.jpg)

**Comment by chuhw** [comment]
感恩，了解了！步驟OK

**Comment by wangpy** [comment]
Great. Please consider closing this ticket if your problem is solved. Thanks.
